// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2UCZ7dkMowbUyTHgk0t8p81W4wgnYy8c',
    appId: '1:655209479941:web:f8dcf3e87b9568a44f416c',
    messagingSenderId: '655209479941',
    projectId: 'hello-flutter-194d1',
    authDomain: 'hello-flutter-194d1.firebaseapp.com',
    storageBucket: 'hello-flutter-194d1.appspot.com',
    measurementId: 'G-LCVX6L428H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkepct-JTXKLnZWk1wQktXxHdhrXP1-JI',
    appId: '1:655209479941:android:a91b41e914c539144f416c',
    messagingSenderId: '655209479941',
    projectId: 'hello-flutter-194d1',
    storageBucket: 'hello-flutter-194d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB9vRYpzMSuVtc9eO0LBuELJPIcFv4rco',
    appId: '1:655209479941:ios:9dc4f5e29d9f4aac4f416c',
    messagingSenderId: '655209479941',
    projectId: 'hello-flutter-194d1',
    storageBucket: 'hello-flutter-194d1.appspot.com',
    iosBundleId: 'com.kyong.hello-app-20231110',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB9vRYpzMSuVtc9eO0LBuELJPIcFv4rco',
    appId: '1:655209479941:ios:99369fa72fd940bb4f416c',
    messagingSenderId: '655209479941',
    projectId: 'hello-flutter-194d1',
    storageBucket: 'hello-flutter-194d1.appspot.com',
    iosBundleId: 'com.example.helloworld',
  );
}
